# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ConsultaMateria.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultaMateria(object):
    def setupUi(self, Dialog, modificar, id_materia):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(541, 175)
        Dialog.setMinimumSize(QtCore.QSize(541, 175))
        Dialog.setMaximumSize(QtCore.QSize(541, 175))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setModal(True)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tx_materia = QtWidgets.QLineEdit(Dialog)
        self.tx_materia.setGeometry(QtCore.QRect(110, 60, 401, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tx_materia.setFont(font)
        self.tx_materia.setText("")
        self.tx_materia.setObjectName("tx_materia")
        self.tx_codigo = QtWidgets.QLineEdit(Dialog)
        self.tx_codigo.setGeometry(QtCore.QRect(110, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tx_codigo.setFont(font)
        self.tx_codigo.setInputMask("")
        self.tx_codigo.setText("")
        self.tx_codigo.setObjectName("tx_codigo")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 501, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Bt_guardar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_guardar.setMaximumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Bt_guardar.setFont(font)
        self.Bt_guardar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_guardar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_guardar.setObjectName("Bt_guardar")
        self.horizontalLayout.addWidget(self.Bt_guardar)
        self.Bt_cancelar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_cancelar.setMaximumSize(QtCore.QSize(161, 41))
        self.Bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_cancelar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_cancelar.setObjectName("Bt_cancelar")
        self.horizontalLayout.addWidget(self.Bt_cancelar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tx_codigo, self.tx_materia)

        from Forms.Materia.ControllerConsultaMateria import ControllerConsultaMateria
        controller = ControllerConsultaMateria(self, Dialog, modificar, id_materia)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Materia"))
        self.label_2.setText(_translate("Dialog", "Materia"))
        self.label.setText(_translate("Dialog", "Código"))
        self.Bt_guardar.setText(_translate("Dialog", "Guardar"))
        self.Bt_cancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
