# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Materias.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Materias(object):
    def setupUi(self, Materias, selectRegister = None, ref_tx_id_materia = None, id_carrera = None, years = None):
        Materias.setObjectName("Materias")
        Materias.resize(823, 480)
        Materias.setMinimumSize(QtCore.QSize(823, 480))
        Materias.setMaximumSize(QtCore.QSize(823, 480))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        Materias.setFont(font)
        Materias.setStyleSheet("background-color: rgb(255, 255, 255);")
        Materias.setModal(True)
        self.bt_nuevo = QtWidgets.QPushButton(Materias)
        self.bt_nuevo.setGeometry(QtCore.QRect(10, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_nuevo.setFont(font)
        self.bt_nuevo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_nuevo.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_nuevo.setAutoDefault(False)
        self.bt_nuevo.setDefault(False)
        self.bt_nuevo.setFlat(False)
        self.bt_nuevo.setObjectName("bt_nuevo")
        self.bt_modificar = QtWidgets.QPushButton(Materias)
        self.bt_modificar.setGeometry(QtCore.QRect(330, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_modificar.setFont(font)
        self.bt_modificar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_modificar.setStyleSheet("background-color:  rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_modificar.setAutoDefault(False)
        self.bt_modificar.setDefault(False)
        self.bt_modificar.setFlat(False)
        self.bt_modificar.setObjectName("bt_modificar")
        self.bt_eliminar = QtWidgets.QPushButton(Materias)
        self.bt_eliminar.setGeometry(QtCore.QRect(650, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_eliminar.setFont(font)
        self.bt_eliminar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_eliminar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_eliminar.setAutoDefault(False)
        self.bt_eliminar.setDefault(False)
        self.bt_eliminar.setFlat(False)
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.radioButton_codigo = QtWidgets.QRadioButton(Materias)
        self.radioButton_codigo.setGeometry(QtCore.QRect(250, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.radioButton_codigo.setFont(font)
        self.radioButton_codigo.setChecked(True)
        self.radioButton_codigo.setObjectName("radioButton_codigo")
        self.radioButton_materia = QtWidgets.QRadioButton(Materias)
        self.radioButton_materia.setGeometry(QtCore.QRect(340, 10, 82, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.radioButton_materia.setFont(font)
        self.radioButton_materia.setObjectName("radioButton_materia")
        self.tx_buscar = QtWidgets.QLineEdit(Materias)
        self.tx_buscar.setGeometry(QtCore.QRect(10, 10, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.tx_buscar.setFont(font)
        self.tx_buscar.setObjectName("tx_buscar")
        self.tableWidget = QtWidgets.QTableWidget(Materias)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 801, 351))
        self.tableWidget.setMaximumSize(QtCore.QSize(801, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color:  rgb(7, 70, 124);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"Verdana\";\n"
"    border: 0px solid #ff0000;\n"
"    height: 32px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    font: 11pt \"Verdana\";\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    selection-background-color: rgb(7, 70, 124);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)

        self.retranslateUi(Materias)
        QtCore.QMetaObject.connectSlotsByName(Materias)
        Materias.setTabOrder(self.tx_buscar, self.radioButton_codigo)
        Materias.setTabOrder(self.radioButton_codigo, self.radioButton_materia)
        Materias.setTabOrder(self.radioButton_materia, self.tableWidget)

        from Forms.Materia.ControllerMaterias import ControllerMaterias
        controller = ControllerMaterias(self, Materias, selectRegister, ref_tx_id_materia, id_carrera, years)

    def retranslateUi(self, Materias):
        _translate = QtCore.QCoreApplication.translate
        Materias.setWindowTitle(_translate("Materias", "Materia"))
        self.bt_nuevo.setText(_translate("Materias", "Nuevo"))
        self.bt_modificar.setText(_translate("Materias", "Modificar"))
        self.bt_eliminar.setText(_translate("Materias", "Eliminar"))
        self.radioButton_codigo.setText(_translate("Materias", "Código"))
        self.radioButton_materia.setText(_translate("Materias", "Materia"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Materias", "Código"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Materias", "Materia"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Materias = QtWidgets.QDialog()
    ui = Ui_Materias()
    ui.setupUi(Materias)
    Materias.show()
    sys.exit(app.exec_())
