# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CarrerasMaterias.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MateriasCarrera(object):
    def setupUi(self, MateriasCarrera):
        MateriasCarrera.setObjectName("MateriasCarrera")
        MateriasCarrera.resize(969, 482)
        MateriasCarrera.setMinimumSize(QtCore.QSize(831, 482))
        MateriasCarrera.setMaximumSize(QtCore.QSize(1000, 482))
        MateriasCarrera.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox = QtWidgets.QGroupBox(MateriasCarrera)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 460, 461))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_codigo_carrera = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_codigo_carrera.setGeometry(QtCore.QRect(230, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_codigo_carrera.setFont(font)
        self.radioButton_codigo_carrera.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_codigo_carrera.setChecked(True)
        self.radioButton_codigo_carrera.setObjectName("radioButton_codigo_carrera")
        self.tableWidgetCarreras = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidgetCarreras.setGeometry(QtCore.QRect(10, 50, 441, 401))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidgetCarreras.setFont(font)
        self.tableWidgetCarreras.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetCarreras.setStyleSheet("QHeaderView::section {\n"
"    background-color:  rgb(7, 70, 124);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"Verdana\";\n"
"    border: 0px solid #ff0000;\n"
"    height: 32px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    font: 11pt \"Verdana\";\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    selection-background-color: rgb(7, 70, 124);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tableWidgetCarreras.setAutoScroll(True)
        self.tableWidgetCarreras.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetCarreras.setTabKeyNavigation(False)
        self.tableWidgetCarreras.setProperty("showDropIndicator", True)
        self.tableWidgetCarreras.setDragEnabled(False)
        self.tableWidgetCarreras.setDragDropOverwriteMode(True)
        self.tableWidgetCarreras.setAlternatingRowColors(True)
        self.tableWidgetCarreras.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetCarreras.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetCarreras.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidgetCarreras.setShowGrid(True)
        self.tableWidgetCarreras.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetCarreras.setWordWrap(True)
        self.tableWidgetCarreras.setCornerButtonEnabled(True)
        self.tableWidgetCarreras.setRowCount(12)
        self.tableWidgetCarreras.setColumnCount(2)
        self.tableWidgetCarreras.setObjectName("tableWidgetCarreras")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCarreras.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCarreras.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCarreras.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCarreras.setItem(0, 1, item)
        self.tableWidgetCarreras.horizontalHeader().setVisible(True)
        self.tableWidgetCarreras.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetCarreras.horizontalHeader().setHighlightSections(False)
        self.tableWidgetCarreras.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetCarreras.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetCarreras.verticalHeader().setVisible(False)
        self.tableWidgetCarreras.verticalHeader().setHighlightSections(True)
        self.tableWidgetCarreras.verticalHeader().setSortIndicatorShown(False)
        self.tx_buscar_carrera = QtWidgets.QLineEdit(self.groupBox)
        self.tx_buscar_carrera.setGeometry(QtCore.QRect(10, 20, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.tx_buscar_carrera.setFont(font)
        self.tx_buscar_carrera.setObjectName("tx_buscar_carrera")
        self.radioButton_nombre_carrera = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_nombre_carrera.setGeometry(QtCore.QRect(300, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_nombre_carrera.setFont(font)
        self.radioButton_nombre_carrera.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_nombre_carrera.setObjectName("radioButton_nombre_carrera")
        self.groupBox_2 = QtWidgets.QGroupBox(MateriasCarrera)
        self.groupBox_2.setGeometry(QtCore.QRect(480, 10, 480, 461))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_codigo_materia = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_codigo_materia.setGeometry(QtCore.QRect(191, 21, 66, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_codigo_materia.setFont(font)
        self.radioButton_codigo_materia.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_codigo_materia.setChecked(True)
        self.radioButton_codigo_materia.setObjectName("radioButton_codigo_materia")
        self.tx_buscar_materia = QtWidgets.QLineEdit(self.groupBox_2)
        self.tx_buscar_materia.setGeometry(QtCore.QRect(10, 20, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.tx_buscar_materia.setFont(font)
        self.tx_buscar_materia.setObjectName("tx_buscar_materia")
        self.radioButton_nombre_materia = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_nombre_materia.setGeometry(QtCore.QRect(263, 21, 75, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_nombre_materia.setFont(font)
        self.radioButton_nombre_materia.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_nombre_materia.setObjectName("radioButton_nombre_materia")
        self.tableWidgetMaterias = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidgetMaterias.setGeometry(QtCore.QRect(10, 50, 461, 351))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidgetMaterias.setFont(font)
        self.tableWidgetMaterias.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetMaterias.setStyleSheet("QHeaderView::section {\n"
"    background-color:  rgb(7, 70, 124);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"Verdana\";\n"
"    border: 0px solid #ff0000;\n"
"    height: 32px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    font: 11pt \"Verdana\";\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    selection-background-color: rgb(7, 70, 124);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tableWidgetMaterias.setAutoScroll(True)
        self.tableWidgetMaterias.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetMaterias.setTabKeyNavigation(False)
        self.tableWidgetMaterias.setProperty("showDropIndicator", True)
        self.tableWidgetMaterias.setDragEnabled(False)
        self.tableWidgetMaterias.setDragDropOverwriteMode(True)
        self.tableWidgetMaterias.setAlternatingRowColors(True)
        self.tableWidgetMaterias.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetMaterias.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetMaterias.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidgetMaterias.setShowGrid(True)
        self.tableWidgetMaterias.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetMaterias.setWordWrap(True)
        self.tableWidgetMaterias.setCornerButtonEnabled(True)
        self.tableWidgetMaterias.setRowCount(10)
        self.tableWidgetMaterias.setColumnCount(4)
        self.tableWidgetMaterias.setObjectName("tableWidgetMaterias")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMaterias.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMaterias.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMaterias.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMaterias.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMaterias.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMaterias.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMaterias.setItem(0, 3, item)
        self.tableWidgetMaterias.horizontalHeader().setVisible(True)
        self.tableWidgetMaterias.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetMaterias.horizontalHeader().setHighlightSections(False)
        self.tableWidgetMaterias.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetMaterias.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetMaterias.verticalHeader().setVisible(False)
        self.tableWidgetMaterias.verticalHeader().setHighlightSections(True)
        self.radioButton_nombre_year = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_nombre_year.setGeometry(QtCore.QRect(344, 21, 48, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_nombre_year.setFont(font)
        self.radioButton_nombre_year.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_nombre_year.setObjectName("radioButton_nombre_year")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 410, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_nuevo = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_nuevo.setMaximumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_nuevo.setFont(font)
        self.bt_nuevo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_nuevo.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_nuevo.setObjectName("bt_nuevo")
        self.horizontalLayout.addWidget(self.bt_nuevo)
        self.bt_eliminar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_eliminar.setMaximumSize(QtCore.QSize(161, 41))
        self.bt_eliminar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_eliminar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.horizontalLayout.addWidget(self.bt_eliminar)
        self.groupBox_2.raise_()
        self.groupBox.raise_()

        self.retranslateUi(MateriasCarrera)
        QtCore.QMetaObject.connectSlotsByName(MateriasCarrera)
        MateriasCarrera.setTabOrder(self.tx_buscar_carrera, self.radioButton_codigo_carrera)
        MateriasCarrera.setTabOrder(self.radioButton_codigo_carrera, self.radioButton_nombre_carrera)
        MateriasCarrera.setTabOrder(self.radioButton_nombre_carrera, self.tableWidgetCarreras)

        from Forms.CarreraMateria.ControllerCarrerasMaterias import ControllerCarrerasMaterias
        controller = ControllerCarrerasMaterias(self, MateriasCarrera).load()

    def retranslateUi(self, MateriasCarrera):
        _translate = QtCore.QCoreApplication.translate
        MateriasCarrera.setWindowTitle(_translate("MateriasCarrera", "Materias por carrera"))
        self.groupBox.setTitle(_translate("MateriasCarrera", "Carreras"))
        self.radioButton_codigo_carrera.setText(_translate("MateriasCarrera", "Código"))
        item = self.tableWidgetCarreras.horizontalHeaderItem(0)
        item.setText(_translate("MateriasCarrera", "Código"))
        item = self.tableWidgetCarreras.horizontalHeaderItem(1)
        item.setText(_translate("MateriasCarrera", "Nombre"))
        __sortingEnabled = self.tableWidgetCarreras.isSortingEnabled()
        self.tableWidgetCarreras.setSortingEnabled(False)
        self.tableWidgetCarreras.setSortingEnabled(__sortingEnabled)
        self.radioButton_nombre_carrera.setText(_translate("MateriasCarrera", "Nombre"))
        self.groupBox_2.setTitle(_translate("MateriasCarrera", "Materias por año de carrera"))
        self.radioButton_codigo_materia.setText(_translate("MateriasCarrera", "Código"))
        self.radioButton_nombre_materia.setText(_translate("MateriasCarrera", "Nombre"))
        item = self.tableWidgetMaterias.horizontalHeaderItem(0)
        item.setText(_translate("MateriasCarrera", "id"))
        item = self.tableWidgetMaterias.horizontalHeaderItem(1)
        item.setText(_translate("MateriasCarrera", "Código"))
        item = self.tableWidgetMaterias.horizontalHeaderItem(2)
        item.setText(_translate("MateriasCarrera", "Nombre"))
        item = self.tableWidgetMaterias.horizontalHeaderItem(3)
        item.setText(_translate("MateriasCarrera", "Año"))
        __sortingEnabled = self.tableWidgetMaterias.isSortingEnabled()
        self.tableWidgetMaterias.setSortingEnabled(False)
        self.tableWidgetMaterias.setSortingEnabled(__sortingEnabled)
        self.radioButton_nombre_year.setText(_translate("MateriasCarrera", "Año"))
        self.bt_nuevo.setText(_translate("MateriasCarrera", "Nuevo"))
        self.bt_eliminar.setText(_translate("MateriasCarrera", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MateriasCarrera = QtWidgets.QDialog()
    ui = Ui_MateriasCarrera()
    ui.setupUi(MateriasCarrera)
    MateriasCarrera.show()
    sys.exit(app.exec_())
