# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ConsultaYear.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultaYear(object):
    def setupUi(self, Dialog, id_carrera):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 133)
        Dialog.setMinimumSize(QtCore.QSize(400, 133))
        Dialog.setMaximumSize(QtCore.QSize(400, 133))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_years = QtWidgets.QLineEdit(Dialog)
        self.tx_years.setGeometry(QtCore.QRect(160, 19, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.tx_years.setFont(font)
        self.tx_years.setObjectName("tx_years")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 19, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Bt_siguiente = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_siguiente.setMaximumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Bt_siguiente.setFont(font)
        self.Bt_siguiente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_siguiente.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_siguiente.setObjectName("Bt_siguiente")
        self.horizontalLayout.addWidget(self.Bt_siguiente)
        self.Bt_cancelar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_cancelar.setMaximumSize(QtCore.QSize(161, 41))
        self.Bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_cancelar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_cancelar.setObjectName("Bt_cancelar")
        self.horizontalLayout.addWidget(self.Bt_cancelar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        from Forms.CarreraMateria.ControllerConsultaYear import ControllerConsultaYear
        controller = ControllerConsultaYear(self, Dialog, id_carrera)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Año de carrera"))
        self.label.setText(_translate("Dialog", "Año de carrera:"))
        self.Bt_siguiente.setText(_translate("Dialog", "Siguiente"))
        self.Bt_cancelar.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
