# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ciclos.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ciclos(object):
    def setupUi(self, Ciclos, selectRegister = None, ref_tx_id_division = None):
        Ciclos.setObjectName("Ciclos")
        Ciclos.resize(824, 479)
        Ciclos.setMinimumSize(QtCore.QSize(824, 479))
        Ciclos.setMaximumSize(QtCore.QSize(824, 479))
        Ciclos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bt_nuevo = QtWidgets.QPushButton(Ciclos)
        self.bt_nuevo.setGeometry(QtCore.QRect(10, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_nuevo.setFont(font)
        self.bt_nuevo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_nuevo.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_nuevo.setAutoDefault(False)
        self.bt_nuevo.setDefault(False)
        self.bt_nuevo.setFlat(False)
        self.bt_nuevo.setObjectName("bt_nuevo")
        self.bt_eliminar = QtWidgets.QPushButton(Ciclos)
        self.bt_eliminar.setGeometry(QtCore.QRect(650, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_eliminar.setFont(font)
        self.bt_eliminar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_eliminar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_eliminar.setAutoDefault(False)
        self.bt_eliminar.setDefault(False)
        self.bt_eliminar.setFlat(False)
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.bt_modificar = QtWidgets.QPushButton(Ciclos)
        self.bt_modificar.setGeometry(QtCore.QRect(330, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_modificar.setFont(font)
        self.bt_modificar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_modificar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_modificar.setAutoDefault(False)
        self.bt_modificar.setDefault(False)
        self.bt_modificar.setFlat(False)
        self.bt_modificar.setObjectName("bt_modificar")
        self.tx_buscar = QtWidgets.QLineEdit(Ciclos)
        self.tx_buscar.setGeometry(QtCore.QRect(10, 10, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.tx_buscar.setFont(font)
        self.tx_buscar.setObjectName("tx_buscar")
        self.radioButton_ciclo = QtWidgets.QRadioButton(Ciclos)
        self.radioButton_ciclo.setGeometry(QtCore.QRect(340, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_ciclo.setFont(font)
        self.radioButton_ciclo.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_ciclo.setObjectName("radioButton_ciclo")
        self.tableWidgetCiclo = QtWidgets.QTableWidget(Ciclos)
        self.tableWidgetCiclo.setGeometry(QtCore.QRect(10, 50, 801, 351))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidgetCiclo.setFont(font)
        self.tableWidgetCiclo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetCiclo.setStyleSheet("QHeaderView::section {\n"
"    background-color:  rgb(7, 70, 124);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"Verdana\";\n"
"    border: 0px solid #ff0000;\n"
"    height: 32px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    font: 11pt \"Verdana\";\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    selection-background-color: rgb(7, 70, 124);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tableWidgetCiclo.setAutoScroll(True)
        self.tableWidgetCiclo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetCiclo.setTabKeyNavigation(False)
        self.tableWidgetCiclo.setProperty("showDropIndicator", True)
        self.tableWidgetCiclo.setDragEnabled(False)
        self.tableWidgetCiclo.setDragDropOverwriteMode(True)
        self.tableWidgetCiclo.setAlternatingRowColors(True)
        self.tableWidgetCiclo.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetCiclo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetCiclo.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidgetCiclo.setShowGrid(True)
        self.tableWidgetCiclo.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetCiclo.setWordWrap(True)
        self.tableWidgetCiclo.setCornerButtonEnabled(True)
        self.tableWidgetCiclo.setRowCount(10)
        self.tableWidgetCiclo.setColumnCount(2)
        self.tableWidgetCiclo.setObjectName("tableWidgetCiclo")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCiclo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCiclo.setHorizontalHeaderItem(1, item)
        self.tableWidgetCiclo.horizontalHeader().setVisible(True)
        self.tableWidgetCiclo.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetCiclo.horizontalHeader().setHighlightSections(False)
        self.tableWidgetCiclo.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetCiclo.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetCiclo.verticalHeader().setVisible(False)
        self.tableWidgetCiclo.verticalHeader().setHighlightSections(True)
        self.radioButton_codigo = QtWidgets.QRadioButton(Ciclos)
        self.radioButton_codigo.setGeometry(QtCore.QRect(250, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_codigo.setFont(font)
        self.radioButton_codigo.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_codigo.setChecked(True)
        self.radioButton_codigo.setObjectName("radioButton_codigo")

        self.retranslateUi(Ciclos)
        QtCore.QMetaObject.connectSlotsByName(Ciclos)

        from Forms.Ciclo.ControllerCiclos import ControllerCiclos
        controller = ControllerCiclos(self, Ciclos, selectRegister, ref_tx_id_division)

    def retranslateUi(self, Ciclos):
        _translate = QtCore.QCoreApplication.translate
        Ciclos.setWindowTitle(_translate("Ciclos", "Ciclos lectivos"))
        self.bt_nuevo.setText(_translate("Ciclos", "Nuevo"))
        self.bt_eliminar.setText(_translate("Ciclos", "Eliminar"))
        self.bt_modificar.setText(_translate("Ciclos", "Modificar"))
        self.radioButton_ciclo.setText(_translate("Ciclos", "Ciclo lectivo"))
        item = self.tableWidgetCiclo.horizontalHeaderItem(0)
        item.setText(_translate("Ciclos", "Código"))
        item = self.tableWidgetCiclo.horizontalHeaderItem(1)
        item.setText(_translate("Ciclos", "Ciclo lectivo"))
        self.radioButton_codigo.setText(_translate("Ciclos", "Código"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ciclos = QtWidgets.QDialog()
    ui = Ui_Ciclos()
    ui.setupUi(Ciclos)
    Ciclos.show()
    sys.exit(app.exec_())
