# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ConsultaCiclo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultaCiclo(object):
    def setupUi(self, Ciclo, modificar, id_ciclo):
        Ciclo.setObjectName("Ciclo")
        Ciclo.resize(542, 175)
        Ciclo.setMinimumSize(QtCore.QSize(542, 175))
        Ciclo.setMaximumSize(QtCore.QSize(542, 175))
        Ciclo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Ciclo)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Ciclo)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tx_ciclo = QtWidgets.QLineEdit(Ciclo)
        self.tx_ciclo.setGeometry(QtCore.QRect(130, 60, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tx_ciclo.setFont(font)
        self.tx_ciclo.setObjectName("tx_ciclo")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Ciclo)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 501, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Bt_guardar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_guardar.setMaximumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Bt_guardar.setFont(font)
        self.Bt_guardar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_guardar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_guardar.setObjectName("Bt_guardar")
        self.horizontalLayout.addWidget(self.Bt_guardar)
        self.Bt_cancelar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_cancelar.setMaximumSize(QtCore.QSize(161, 41))
        self.Bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_cancelar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_cancelar.setObjectName("Bt_cancelar")
        self.horizontalLayout.addWidget(self.Bt_cancelar)
        self.tx_codigo = QtWidgets.QLineEdit(Ciclo)
        self.tx_codigo.setGeometry(QtCore.QRect(130, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tx_codigo.setFont(font)
        self.tx_codigo.setInputMask("")
        self.tx_codigo.setText("")
        self.tx_codigo.setObjectName("tx_codigo")

        self.retranslateUi(Ciclo)
        QtCore.QMetaObject.connectSlotsByName(Ciclo)

        from Forms.Ciclo.ControllerConsultaCiclo import ControllerConsultaCiclo
        controller = ControllerConsultaCiclo(self, Ciclo, modificar, id_ciclo)

    def retranslateUi(self, Ciclo):
        _translate = QtCore.QCoreApplication.translate
        Ciclo.setWindowTitle(_translate("Ciclo", "Ciclo"))
        self.label.setText(_translate("Ciclo", "Código"))
        self.label_2.setText(_translate("Ciclo", "Ciclo lectivo"))
        self.Bt_guardar.setText(_translate("Ciclo", "Guardar"))
        self.Bt_cancelar.setText(_translate("Ciclo", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ciclo = QtWidgets.QDialog()
    ui = Ui_Ciclo()
    ui.setupUi(Ciclo)
    Ciclo.show()
    sys.exit(app.exec_())
