# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Carreras.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carreras(object):
    def setupUi(self, Dialog, selectRegister = None, id_carrera = None):
        Dialog.setObjectName("Dialog")
        Dialog.resize(824, 479)
        Dialog.setMinimumSize(QtCore.QSize(824, 479))
        Dialog.setMaximumSize(QtCore.QSize(824, 479))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton_codigo = QtWidgets.QRadioButton(Dialog)
        self.radioButton_codigo.setGeometry(QtCore.QRect(250, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_codigo.setFont(font)
        self.radioButton_codigo.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_codigo.setChecked(True)
        self.radioButton_codigo.setObjectName("radioButton_codigo")
        self.tableWidgetCarrera = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetCarrera.setGeometry(QtCore.QRect(10, 50, 801, 351))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidgetCarrera.setFont(font)
        self.tableWidgetCarrera.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidgetCarrera.setStyleSheet("QHeaderView::section {\n"
"    background-color:  rgb(7, 70, 124);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"Verdana\";\n"
"    border: 0px solid #ff0000;\n"
"    height: 32px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    font: 11pt \"Verdana\";\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    selection-background-color: rgb(7, 70, 124);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tableWidgetCarrera.setAutoScroll(True)
        self.tableWidgetCarrera.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetCarrera.setTabKeyNavigation(False)
        self.tableWidgetCarrera.setProperty("showDropIndicator", True)
        self.tableWidgetCarrera.setDragEnabled(False)
        self.tableWidgetCarrera.setDragDropOverwriteMode(True)
        self.tableWidgetCarrera.setAlternatingRowColors(True)
        self.tableWidgetCarrera.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetCarrera.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetCarrera.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidgetCarrera.setShowGrid(True)
        self.tableWidgetCarrera.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetCarrera.setWordWrap(True)
        self.tableWidgetCarrera.setCornerButtonEnabled(True)
        self.tableWidgetCarrera.setRowCount(10)
        self.tableWidgetCarrera.setColumnCount(2)
        self.tableWidgetCarrera.setObjectName("tableWidgetCarrera")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCarrera.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCarrera.setHorizontalHeaderItem(1, item)
        self.tableWidgetCarrera.horizontalHeader().setVisible(True)
        self.tableWidgetCarrera.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetCarrera.horizontalHeader().setHighlightSections(False)
        self.tableWidgetCarrera.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetCarrera.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetCarrera.verticalHeader().setVisible(False)
        self.tableWidgetCarrera.verticalHeader().setHighlightSections(True)
        self.radioButton_nombre = QtWidgets.QRadioButton(Dialog)
        self.radioButton_nombre.setGeometry(QtCore.QRect(340, 10, 82, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_nombre.setFont(font)
        self.radioButton_nombre.setFocusPolicy(QtCore.Qt.TabFocus)
        self.radioButton_nombre.setObjectName("radioButton_nombre")
        self.tx_buscar_carrera = QtWidgets.QLineEdit(Dialog)
        self.tx_buscar_carrera.setGeometry(QtCore.QRect(10, 10, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.tx_buscar_carrera.setFont(font)
        self.tx_buscar_carrera.setObjectName("tx_buscar_carrera")
        self.bt_modificar = QtWidgets.QPushButton(Dialog)
        self.bt_modificar.setGeometry(QtCore.QRect(330, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_modificar.setFont(font)
        self.bt_modificar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_modificar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_modificar.setAutoDefault(False)
        self.bt_modificar.setDefault(False)
        self.bt_modificar.setFlat(False)
        self.bt_modificar.setObjectName("bt_modificar")
        self.bt_nuevo = QtWidgets.QPushButton(Dialog)
        self.bt_nuevo.setGeometry(QtCore.QRect(10, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_nuevo.setFont(font)
        self.bt_nuevo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_nuevo.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_nuevo.setAutoDefault(False)
        self.bt_nuevo.setDefault(False)
        self.bt_nuevo.setFlat(False)
        self.bt_nuevo.setObjectName("bt_nuevo")
        self.bt_eliminar = QtWidgets.QPushButton(Dialog)
        self.bt_eliminar.setGeometry(QtCore.QRect(650, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_eliminar.setFont(font)
        self.bt_eliminar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_eliminar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_eliminar.setAutoDefault(False)
        self.bt_eliminar.setDefault(False)
        self.bt_eliminar.setFlat(False)
        self.bt_eliminar.setObjectName("bt_eliminar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tx_buscar_carrera, self.radioButton_codigo)
        Dialog.setTabOrder(self.radioButton_codigo, self.radioButton_nombre)
        Dialog.setTabOrder(self.radioButton_nombre, self.tableWidgetCarrera)

        from Forms.Carrera.ControllerCarreras import ControllerCarreras
        controller = ControllerCarreras(self, Dialog, selectRegister, id_carrera)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Carreras"))
        self.radioButton_codigo.setText(_translate("Dialog", "Código"))
        item = self.tableWidgetCarrera.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Código"))
        item = self.tableWidgetCarrera.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nombre"))
        self.radioButton_nombre.setText(_translate("Dialog", "Nombre"))
        self.bt_modificar.setText(_translate("Dialog", "Modificar"))
        self.bt_nuevo.setText(_translate("Dialog", "Nuevo"))
        self.bt_eliminar.setText(_translate("Dialog", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
