# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ConsultaSede.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultaSede(object):
    def setupUi(self, ConsultaSede, modificar = False, id_sede = None):
        ConsultaSede.setObjectName("ConsultaSede")
        ConsultaSede.resize(542, 175)
        ConsultaSede.setMinimumSize(QtCore.QSize(542, 175))
        ConsultaSede.setMaximumSize(QtCore.QSize(542, 175))
        ConsultaSede.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tx_codigo = QtWidgets.QLineEdit(ConsultaSede)
        self.tx_codigo.setGeometry(QtCore.QRect(100, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tx_codigo.setFont(font)
        self.tx_codigo.setInputMask("")
        self.tx_codigo.setText("")
        self.tx_codigo.setObjectName("tx_codigo")
        self.label = QtWidgets.QLabel(ConsultaSede)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ConsultaSede)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ConsultaSede)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 501, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Bt_guardar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_guardar.setMaximumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Bt_guardar.setFont(font)
        self.Bt_guardar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_guardar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_guardar.setObjectName("Bt_guardar")
        self.horizontalLayout.addWidget(self.Bt_guardar)
        self.Bt_cancelar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Bt_cancelar.setMaximumSize(QtCore.QSize(161, 41))
        self.Bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Bt_cancelar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.Bt_cancelar.setObjectName("Bt_cancelar")
        self.horizontalLayout.addWidget(self.Bt_cancelar)
        self.tx_sede = QtWidgets.QLineEdit(ConsultaSede)
        self.tx_sede.setGeometry(QtCore.QRect(100, 60, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tx_sede.setFont(font)
        self.tx_sede.setObjectName("tx_sede")

        self.retranslateUi(ConsultaSede)
        QtCore.QMetaObject.connectSlotsByName(ConsultaSede)

        from Forms.Sede.ControllerConsultaSede import ControllerConsultaSede
        controller = ControllerConsultaSede(self, ConsultaSede, modificar, id_sede)

    def retranslateUi(self, ConsultaSede):
        _translate = QtCore.QCoreApplication.translate
        ConsultaSede.setWindowTitle(_translate("ConsultaSede", "Sede"))
        self.label.setText(_translate("ConsultaSede", "Código"))
        self.label_2.setText(_translate("ConsultaSede", "Sede"))
        self.Bt_guardar.setText(_translate("ConsultaSede", "Guardar"))
        self.Bt_cancelar.setText(_translate("ConsultaSede", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConsultaSede = QtWidgets.QDialog()
    ui = Ui_ConsultaSede()
    ui.setupUi(ConsultaSede)
    ConsultaSede.show()
    sys.exit(app.exec_())
