# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Clases.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clases(object):
    def setupUi(self, Dialog, selectRegister = None):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(830, 480)
        Dialog.setMinimumSize(QtCore.QSize(830, 480))
        Dialog.setMaximumSize(QtCore.QSize(830, 480))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setModal(True)
        self.radioButton_division = QtWidgets.QRadioButton(Dialog)
        self.radioButton_division.setGeometry(QtCore.QRect(251, 11, 70, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_division.setFont(font)
        self.radioButton_division.setChecked(True)
        self.radioButton_division.setObjectName("radioButton_division")
        self.radioButton_apellido = QtWidgets.QRadioButton(Dialog)
        self.radioButton_apellido.setGeometry(QtCore.QRect(382, 11, 70, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_apellido.setFont(font)
        self.radioButton_apellido.setObjectName("radioButton_apellido")
        self.bt_eliminar = QtWidgets.QPushButton(Dialog)
        self.bt_eliminar.setGeometry(QtCore.QRect(660, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_eliminar.setFont(font)
        self.bt_eliminar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_eliminar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_eliminar.setAutoDefault(False)
        self.bt_eliminar.setDefault(False)
        self.bt_eliminar.setFlat(False)
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 811, 351))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color:  rgb(7, 70, 124);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"Verdana\";\n"
"    border: 0px solid #ff0000;\n"
"    height: 32px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    font: 11pt \"Verdana\";\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    selection-background-color: rgb(7, 70, 124);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tx_buscar = QtWidgets.QLineEdit(Dialog)
        self.tx_buscar.setGeometry(QtCore.QRect(10, 10, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.tx_buscar.setFont(font)
        self.tx_buscar.setStyleSheet("")
        self.tx_buscar.setObjectName("tx_buscar")
        self.radioButton_dni = QtWidgets.QRadioButton(Dialog)
        self.radioButton_dni.setGeometry(QtCore.QRect(327, 11, 49, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_dni.setFont(font)
        self.radioButton_dni.setObjectName("radioButton_dni")
        self.bt_modificar = QtWidgets.QPushButton(Dialog)
        self.bt_modificar.setGeometry(QtCore.QRect(330, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_modificar.setFont(font)
        self.bt_modificar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_modificar.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_modificar.setAutoDefault(False)
        self.bt_modificar.setDefault(False)
        self.bt_modificar.setFlat(False)
        self.bt_modificar.setObjectName("bt_modificar")
        self.bt_nuevo = QtWidgets.QPushButton(Dialog)
        self.bt_nuevo.setGeometry(QtCore.QRect(10, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_nuevo.setFont(font)
        self.bt_nuevo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_nuevo.setStyleSheet("background-color: rgb(7, 70, 124);\n"
"font: 18pt \"Verdana\";\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bt_nuevo.setAutoDefault(False)
        self.bt_nuevo.setDefault(False)
        self.bt_nuevo.setFlat(False)
        self.bt_nuevo.setObjectName("bt_nuevo")
        self.radioButton_nombre = QtWidgets.QRadioButton(Dialog)
        self.radioButton_nombre.setGeometry(QtCore.QRect(458, 11, 75, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_nombre.setFont(font)
        self.radioButton_nombre.setObjectName("radioButton_nombre")
        self.radioButton_entrada = QtWidgets.QRadioButton(Dialog)
        self.radioButton_entrada.setGeometry(QtCore.QRect(539, 11, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_entrada.setFont(font)
        self.radioButton_entrada.setObjectName("radioButton_entrada")
        self.radioButton_salida = QtWidgets.QRadioButton(Dialog)
        self.radioButton_salida.setGeometry(QtCore.QRect(618, 11, 59, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_salida.setFont(font)
        self.radioButton_salida.setObjectName("radioButton_salida")
        self.radioButton_dia = QtWidgets.QRadioButton(Dialog)
        self.radioButton_dia.setGeometry(QtCore.QRect(683, 11, 43, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.radioButton_dia.setFont(font)
        self.radioButton_dia.setObjectName("radioButton_dia")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tx_buscar, self.radioButton_division)
        Dialog.setTabOrder(self.radioButton_division, self.radioButton_dni)
        Dialog.setTabOrder(self.radioButton_dni, self.radioButton_apellido)
        Dialog.setTabOrder(self.radioButton_apellido, self.tableWidget)

        from Forms.Clase.ControllerClases import ControllerClases
        controller = ControllerClases(self, Dialog, selectRegister)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Clases"))
        self.radioButton_division.setText(_translate("Dialog", "División"))
        self.radioButton_apellido.setText(_translate("Dialog", "Apellido"))
        self.bt_eliminar.setText(_translate("Dialog", "Eliminar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Código"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "División"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "DNI"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Apellido"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Entrada"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Salida"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Día"))
        self.radioButton_dni.setText(_translate("Dialog", "DNI"))
        self.bt_modificar.setText(_translate("Dialog", "Modificar"))
        self.bt_nuevo.setText(_translate("Dialog", "Nuevo"))
        self.radioButton_nombre.setText(_translate("Dialog", "Nombre"))
        self.radioButton_entrada.setText(_translate("Dialog", "Entrada"))
        self.radioButton_salida.setText(_translate("Dialog", "Salida"))
        self.radioButton_dia.setText(_translate("Dialog", "Dia"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
